//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("PartSession")]
    public partial class PartSession
    {
        public PartSession(int? idparticipant, int? idsessionFormation)
        {
            this.idparticipant = idparticipant;
            this.idsessionFormation = idsessionFormation;
        }

        public PartSession( Participant participant, SessionFormation sessionFormation)
        {
           
            Participant = participant;
            SessionFormation = sessionFormation;
        }
        public PartSession() { }

        [Key]
        public int idpartsession { get; set; }
        public Nullable<int> idparticipant { get; set; }
        public Nullable<int> idsessionFormation { get; set; }
    
        public virtual Participant Participant { get; set; }
        public virtual SessionFormation SessionFormation { get; set; }
    }
}
