//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("Reunionform")]
    public partial class Reunionform
    {
        public Reunionform(int? idformateur, int? idreunion)
        {
            this.idformateur = idformateur;
            this.idreunion = idreunion;
        }

        public Reunionform(Formateur formateur, Reunion reunion)
        {
            Formateur = formateur;
            Reunion = reunion;
        }
        public Reunionform( )
        {
     
        }

    
        public Nullable<int> idformateur { get; set; }
        public Nullable<int> idreunion { get; set; }
        [Key]
        public int idreunionform { get; set; }
    
        public virtual Formateur Formateur { get; set; }
        public virtual Reunion Reunion { get; set; }
    }
}
