//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("Reunion")]

    public partial class Reunion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Reunion()
        {
            this.Reunionform = new HashSet<Reunionform>();
        }

        public Reunion(string sujet, DateTime dateheure)
        {
            this.sujet = sujet;
            this.dateheure = dateheure;
            this.idresponsable = 1;
        }
   
        [Key]
        public int idreunion { get; set; }
        public string sujet { get; set; }
        public System.DateTime dateheure { get; set; }
         public int idresponsable { get; set; }
    
        public virtual Responsable Responsable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reunionform> Reunionform { get; set; }
    }
}
